create table FILM
(
    MULTIMEDIA_ID NUMBER not null
        constraint FILM_PK
            primary key
        constraint FILM_MULTIMEDIA_ID_FK
            references MULTIMEDIA
                on delete cascade,
    EV            NUMBER,
    HOSSZ         NUMBER
)
/

INSERT INTO VOROS.FILM (MULTIMEDIA_ID, EV, HOSSZ) VALUES (8, 2020, 150);
INSERT INTO VOROS.FILM (MULTIMEDIA_ID, EV, HOSSZ) VALUES (7, 2019, 149);
INSERT INTO VOROS.FILM (MULTIMEDIA_ID, EV, HOSSZ) VALUES (9, 2019, 118);
INSERT INTO VOROS.FILM (MULTIMEDIA_ID, EV, HOSSZ) VALUES (10, 2020, 100);
INSERT INTO VOROS.FILM (MULTIMEDIA_ID, EV, HOSSZ) VALUES (11, 1952, 85);
INSERT INTO VOROS.FILM (MULTIMEDIA_ID, EV, HOSSZ) VALUES (12, 2020, 101);