create table HANGOSKONYV
(
    KONYV_ID  NUMBER not null
        constraint HANGOSKONYV_KONYV_ID_FK
            references KONYV
                on delete cascade,
    ELBESZELO VARCHAR2(100),
    HOSSZ     NUMBER
)
/

create unique index HANGOSKONYV_KONYV_ID_UINDEX
    on HANGOSKONYV (KONYV_ID)
/

alter table HANGOSKONYV
    add constraint HANGOSKONYV_PK
        primary key (KONYV_ID)
/

INSERT INTO VOROS.HANGOSKONYV (KONYV_ID, ELBESZELO, HOSSZ) VALUES (46, 'Csőre Gábor', 112);
INSERT INTO VOROS.HANGOSKONYV (KONYV_ID, ELBESZELO, HOSSZ) VALUES (48, 'Hirtling István', 72);
INSERT INTO VOROS.HANGOSKONYV (KONYV_ID, ELBESZELO, HOSSZ) VALUES (47, 'Szacsvay László', 81);
INSERT INTO VOROS.HANGOSKONYV (KONYV_ID, ELBESZELO, HOSSZ) VALUES (22, 'Fekete Ernő', 123);
INSERT INTO VOROS.HANGOSKONYV (KONYV_ID, ELBESZELO, HOSSZ) VALUES (21, 'Mácsai Pál', 142);