create table MULTIMEDIA
(
    ID        NUMBER generated as identity,
    CIM       VARCHAR2(100) not null,
    AR        NUMBER        not null,
    ELERESIUT VARCHAR2(200)
)
/

create unique index MULTIMEDIA_ID_UINDEX
    on MULTIMEDIA (ID)
/

alter table MULTIMEDIA
    add constraint MULTIMEDIA_PK
        primary key (ID)
/

INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (3, 'Evermore', 5000, null);
INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (4, 'Positions', 12000, null);
INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (5, 'Revelación ', 5000, null);
INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (6, 'The Highlights', 5000, null);
INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (7, 'Az AranyPinty', 1500, null);
INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (8, 'Tenet', 2800, null);
INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (9, 'Judy', 3000, null);
INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (10, 'Sonic, a sündisznó', 2800, null);
INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (11, 'Délidő', 1800, null);
INSERT INTO VOROS.MULTIMEDIA (ID, CIM, AR, ELERESIUT) VALUES (12, 'Dolittle', 4700, null);