create table ANTIKVARKONYV
(
    KONYV_ID NUMBER not null
        constraint ANTIKVARKONYV_KONYV_ID_FK
            references KONYV
                on delete cascade,
    KOR      NUMBER,
    ALLAPOT  VARCHAR2(100)
)
/

create unique index ANTIKVARKONYV_KONYV_ID_UINDEX
    on ANTIKVARKONYV (KONYV_ID)
/

alter table ANTIKVARKONYV
    add constraint ANTIKVARKONYV_PK
        primary key (KONYV_ID)
/

INSERT INTO VOROS.ANTIKVARKONYV (KONYV_ID, KOR, ALLAPOT) VALUES (25, 2, 'jó');
INSERT INTO VOROS.ANTIKVARKONYV (KONYV_ID, KOR, ALLAPOT) VALUES (52, 1, 'jó');
INSERT INTO VOROS.ANTIKVARKONYV (KONYV_ID, KOR, ALLAPOT) VALUES (30, 1, 'jó');
INSERT INTO VOROS.ANTIKVARKONYV (KONYV_ID, KOR, ALLAPOT) VALUES (39, 6, 'jó');
INSERT INTO VOROS.ANTIKVARKONYV (KONYV_ID, KOR, ALLAPOT) VALUES (50, 2, 'jó');